import math
import random
import numpy as np

BATTERY_CAPACITY_LIST = [55, 75, 80, 100]  # battery capacity set (kWh)
SoC_INI_RANGE = (0.1, 0.5)  # initial SoC range
DEMAND_SoC_MINI_RANGE = (0.2, 0.4)  # minimal SoC demand range
TIME_COST = 5  # time cost ($/h)
COST_EST = 0.25 + (3 + TIME_COST) / 100  # estimated pay ($) for 1 kWh energy (including price, parking fee, time cost)
ALPHA_RANGE = (COST_EST * 0.8, COST_EST * 1.2)
LEAVE_U_DIFF_MAX = 10 # maximum utility different for leaving with maximum probability
LEAVE_PROB_MAX = 0.3 # maximum leaving probability range


class EV:
    """
    Class for EV user
    """

    def __init__(self, time_arrival,
                 u_tol=0):
        # some const parameters
        self.battery_capacity = random.choice(BATTERY_CAPACITY_LIST)     # battery capacity, unit: kWh, (E_i)
        self.SoC_ini = np.random.uniform(SoC_INI_RANGE[0],SoC_INI_RANGE[1]) # initial SoC
        self.demand_min = np.random.uniform(DEMAND_SoC_MINI_RANGE[0], DEMAND_SoC_MINI_RANGE[1]) * self.battery_capacity # minimal demand (kwh)
        self.alpha = np.random.uniform(ALPHA_RANGE[0], ALPHA_RANGE[1])  # parameter used to calculate the utility
                                                                        # represents the value of 1 kWh for the user
        self.leave_prob_max = LEAVE_PROB_MAX # maximum leaving probability
        self.u_tolerance = u_tol # utility tolerance for selecting stations ($)

        # time related variables
        self.time_arrival = time_arrival  # arrival time at one station
        self.time_assigned = None  # time when EV is assigned to a charger
        self.time_last_charged = None  # last time when charge_and_pay was called

        # state variables
        self.SoC = self.SoC_ini    # current SoC
        self.SoE = self.SoC * self.battery_capacity  # current SoE
        self.demand_ini = None  # initial optimal demand (kwh)
        self.demand = None # current demand/ remaining demand (kwh)
        self.selected_station = None # selected station name
        self.utility_ini = None # initial utility under the selected station
        self.price = None  # received charging price ($/kwh)
        self.parking_fee = None # received parking fee ($/h)
        self.cumulative_revenue = 0.0  # cumulative revenue generated by this EV
        self.last_step_energy_delivered_kwh = 0.0
        self.last_step_payment = 0.0


    def charge_and_accumulate_revenue(self, charging_power, current_time, dt):
        """
        Simulate charging process with precise time tracking and revenue accumulation.
        
        This method:
        1. Tracks when EV is assigned to a charger
        2. Calculates energy delivered based on actual time spent
        3. Accumulates revenue over EV's lifetime
        
        Input:
            charging_power: charging power (kW)
            current_time: current simulation time (s)
            dt: time duration of this step (s)
        
        Output:
            energy_delivered: actually energy delivered (kWh)
            payment: payment for this step ($)
        """
        
        # Initialize time tracking on first call
        if self.time_assigned is None:
            self.time_assigned = current_time
            self.time_last_charged = current_time
            # On first call, no actual charging time has passed yet
            return 0.0, 0.0
        
        # Calculate time since last charge call (actual dt for this EV)
        dt_actual = current_time - self.time_last_charged
        
        # Update battery state based on actual time
        SoE_pre = self.SoE
        self.SoE = min(self.SoE + charging_power * dt_actual / 3600, self.battery_capacity)
        self.SoC = self.SoE / self.battery_capacity
        energy_delivered = self.SoE - SoE_pre
        
        # Calculate charging revenue for this step.
        # Parking fee is intentionally excluded from the RL reward target so
        # the station objective aligns with IDP profit (charging revenue - costs).
        if charging_power > 0 and energy_delivered > 0:
            payment = energy_delivered * self.price
        else:
            payment = 0.0
        
        self.last_step_energy_delivered_kwh = float(energy_delivered)
        self.last_step_payment = float(payment)

        # Accumulate revenue
        self.cumulative_revenue += payment
        
        # Update time tracking
        self.time_last_charged = current_time
        
        return energy_delivered, payment


    def get_utility(self, x, price, parking_fee, charging_power):

        utility = self.alpha * self.battery_capacity * math.log(1 + x / self.SoE) \
                   - price * x - (parking_fee + TIME_COST) * (x / charging_power)

        return utility


    def get_optimal_demand(self, price, parking_fee, charging_power): #
        """
        Get the optimal demand by maximizing the utility function based on the price, parking fee, SoC, etc.
        Note: the peak of utility function does not ensure the utility is greater than 0
              It is a private user method that the station cannot know
        Inputs:
            price: charging price ($/kWh)
            parking_fee: parking fee ($/h)
            charging_power: charging power (kW)
        Output:
            x_max: the optimal demand (kWh)
            utility: utility value ($)
        """

        x_pole = self.alpha*self.battery_capacity/(price + (parking_fee+TIME_COST)/charging_power)  - self.SoE # it is calculated through the derivative of the utility function
        x_up = self.battery_capacity - self.SoE # maximum possible demand
        if x_pole <= self.demand_min:
            x_opt = self.demand_min
        elif x_pole >= x_up:
            x_opt = x_up
        else:
            x_opt = x_pole

        utility = self.get_utility(x_opt, price, parking_fee, charging_power)

        return  x_opt, utility

    def choose_station(self, evsts_info):
        """
        select a charging station according to provided parameters of each station

        Inputs:
            evsts_info: a dictionary of each station's state information, e.g.,
            {
              "evst_1": {"price": 0.22, "parking_fee": 3, "charging_power": 100, "num_users": 2},
              "evst_2": {"price": 0.25, "parking_fee": 3, "charging_power": 50, "num_users": 1},
              ...
            }

        Output:
            station_name: name of the selected station, (None if leave)
            x_opt: optimal demand at the selected station
            utility: optimal utility at the selected station
        """

        # 1. find the best station and best available station
        best_st = None         # best station name
        best_u = -float('inf') # utility of the best station
        best_avail_st = None   # best available station name
        best_avail_u = -float('inf') # utility of the best available station


        evsts_x_u = {key: {} for key in evsts_info}
        available_list = []
        for name, info in evsts_info.items():
            x, u = self.get_optimal_demand(info["price"], info["parking_fee"], info["charging_power"])
            evsts_x_u[name]['x'] = x
            evsts_x_u[name]['u'] = u
            if u > best_u:
                best_u = u
                best_st = name
            if info["num_chargers"] - info["num_users"] > 0 and u > best_avail_u:
                available_list.append(name)
                best_avail_u = u
                best_avail_st = name


        # 2. if no available station, return None
        if not available_list:
            return None, None, None

        # 3. calculate the leaving probability based on the distance between best_u and best_avail_u
        p_leave, u_distance = self.get_leave_probability(best_u, best_avail_u)


        if random.random() < p_leave: # leave with probability
            return None, None, None
        else:
            # get candidate list with equal selection probability
            # (utility difference within tolerance will be considered)
            candidate_list = []
            for name in available_list:
                    d = best_avail_u - evsts_x_u[name]['u']
                    if d <= self.u_tolerance:
                        candidate_list.append(name)
            self.selected_station = random.choice(candidate_list)
            # self.selected_station = best_avail_st
            self.demand = self.demand_ini = evsts_x_u[self.selected_station]['x']
            self.utility_ini = evsts_x_u[self.selected_station]['u']
            self.price = evsts_info[self.selected_station]['price']
            self.parking_fee = evsts_info[self.selected_station]['parking_fee']
            return self.selected_station, evsts_x_u[self.selected_station]['x'], evsts_x_u[self.selected_station]['u']

    def get_leave_probability(self, best_u, u):
        """
        calculate the leaving probability based on the distance between the best utility and the best available utility.
        make sure best_u always >= u
        """
        distance = best_u - u # must >= 0
        diff_r = min(distance / LEAVE_U_DIFF_MAX, 1)
        p = self.leave_prob_max * diff_r
        return p, distance



    def get_demand(self):
        """
        get remaining demand
        """

        return self.demand_ini + self.SoC_ini * self.battery_capacity - self.SoE








if __name__ == "__main__":

    # test EV station selection
    ev = EV(time_arrival=0)

    evsts_par =  {
              "evst_1": {"price": 0.28, "parking_fee": 3, "charging_power": 100, "availability": True},
              "evst_2": {"price": 0.4, "parking_fee": 3, "charging_power": 150, "availability": True},
              "evst_3": {"price": 0.25, "parking_fee": 3, "charging_power": 50, "availability": False}}
    # ev.leave_prob_max=0.9
    station_name, x_opt, u_opt = ev.choose_station(evsts_par)
    print(station_name, x_opt, u_opt)
    print("")

    if station_name:

        # input parameters
        price = evsts_par[station_name]["price"]  # 充电价格 ($/kWh)
        parking_fee = evsts_par[station_name]["parking_fee"]  # 停车费 ($/h)
        charging_power = evsts_par[station_name]["charging_power"]  # 充电功率 (kW)

        print("----------------------------------")
        print("Battery Capacity (kWh):", ev.battery_capacity)
        print("SoC:", ev.SoC_ini)
        print("SoE:", ev.SoE)
        print("alpha:", ev.alpha)
        print("leave_prob_max:", ev.leave_prob_max)
        print("demand_min:", ev.demand_min)
        print("Charging Price ($/kWh):", price)
        print("Parking Fee ($/h):", parking_fee)
        print("Time Cost ($/h):", TIME_COST)
        print("Charging Power (kW):", charging_power)
        print("")

        # test different demand
        test_values = range(0, int(ev.battery_capacity-ev.SoE), 5)  # 单位：kWh
        for x in test_values:
            util = ev.get_utility(x, price, parking_fee, charging_power)
            print(f"x = {x} kWh, U = {util:.5f}")

        print("")
        # 求最佳充电量以及对应效用
        x_opt, util_opt = ev.get_optimal_demand(price, parking_fee, charging_power)
        print(f"x_opt = {x_opt} kWh, U_opt = {util_opt:.5f}")

    else:
        print("The user leave!")